updating codebase

diff --git a/next/Dockerfile.production b/next/Dockerfile.production
--- a/next/Dockerfile.production
+++ b/next/Dockerfile.production
@@ -1,4 +1,7 @@
-FROM node:20.8-alpine3.18 AS base
+FROM node:18-alpine AS base
+# 16-alpine
+
+#Next:13.4.12 works
 
 ENV LANG=C.UTF-8
 
@@ -11,22 +14,24 @@ WORKDIR /web
 
 COPY --link package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 
-RUN npm ci
-
+RUN \
+  if [ -f yarn.lock ]; then yarn --network-timeout 100000; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 FROM base AS builder
 
 WORKDIR /web
 
-COPY --from=deps --link /web/node_modules ./node_modules
+COPY --from=deps /web/node_modules ./node_modules
 
-COPY --link . .
+COPY . .
 
 COPY ./next.config.js next.config.js
 
 # Using buildx Google Inter font will fail unless on VPN
 
-RUN npm run build
+RUN yarn build
 
 
 FROM base AS runner
@@ -35,16 +40,19 @@ WORKDIR /web
 
 ENV NODE_ENV=production
 
-COPY --from=builder --link /web/public ./public
-
 RUN : \
 && adduser --system --uid 1001 nextjs \
 && addgroup --system --gid 1001 nodejs \
-&& mkdir .next \
-&& chown nextjs:nodejs .next\
 && :
 
-COPY --from=builder --link /web/next.config.js next.config.js
+COPY --from=builder /web/public ./public
+
+RUN : \
+&& mkdir .next \
+&& chown nextjs:nodejs .next \
+&& :
+
+COPY --from=builder /web/next.config.js next.config.js
 
 COPY --from=builder --chown=nextjs:node /web/.next/standalone ./
 
@@ -63,4 +71,5 @@ USER nextjs
 
 EXPOSE 3000
 
+#ENV HOSTNAME "0.0.0.0"
 CMD ["node", "server.js"]
